name: IronCraft
version: ${project.version}
main: net.dohaw.ironcraft.IronCraftPlugin
api-version: 1.16

commands:
  diamondcraft:
    permission: ironcraft.admin
    description: "The base command for this plugin"