name: IronCraft
version: ${project.version}
main: com.nthbyte.ironcraft.IronCraftPlugin
api-version: 1.16
depend:
  - ProtocolLib
  - Citizens

commands:
  ironcraft:
    permission: ironcraft.admin
    description: "The base command for this plugin"
    aliases:
      - ic
      - ironc